name: "Dataset: Dev"

on: push

jobs:
  run-node-ssg-dev:
    name: "[Dataset: Dev] Eleventy, Gatsby, Next, Nuxt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Install SSG Dependencies
        run: cd ssg/eleventy && npm install
      - name: Run Build
        run: node lib/run.js dev --generators eleventy gatsby next nuxt
        env:
          HASURA_SECRET: ${{ secrets.HASURA_SECRET }}
          HASURA_URL: ${{ secrets.HASURA_URL }}
