name: "Dataset: Dev"

on: push

jobs:
  run-eleventy-dev:
    name: "[Dataset: Dev] Eleventy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: node lib/run.js dev --generators eleventy
        env:
          HASURA_SECRET: ${{ secrets.HASURA_SECRET }}
          HASURA_URL: ${{ secrets.HASURA_URL }}
