name: "Dataset: Dev"

on: push

jobs:
  run-ssg-dev:
    name: "Dataset: Dev"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Install Eleventy Dependencies
        run: cd ssg/eleventy && npm install
      - name: Install Gatsby Dependencies
        run: cd ssg/gatsby && npm install
      - name: Install Next Dependencies
        run: cd ssg/next && npm install
      - name: Install Nuxt Dependencies
        run: cd ssg/nuxt && npm install
      - name: Run Build
        run: node lib/run.js dev --generators eleventy gatsby next nuxt
        env:
          HASURA_SECRET: ${{ secrets.HASURA_SECRET }}
          HASURA_URL: ${{ secrets.HASURA_URL }}
